name: mfst
title: Mikaey's Flash Stress Test
summary: Flash media stress test program
description: |
  Mikaey's Flash Stress Test is a program to stress test flash media to the
  point of failure -- and possibly beyond. It detects whether a storage
  device is fake flash, speed tests the device, and stress tests it.

license: GPL-3.0-or-later
contact: mikaey@bahjeez.com
issues: https://github.com/mikaey/mfst/issues
source-code: https://github.com/mikaey/mfst
website: https://github.com/mikaey/mfst

base: core24
version: '0.4'
grade: stable
confinement: strict

apps:
  mfst:
    command: usr/bin/mfst
    plugs:
      - block-devices
      - hardware-observe
      - raw-usb
      - network
      - home
      - removable-media

parts:
  mfst:
    plugin: autotools
    source: .
    autotools-configure-parameters:
      - --prefix=/usr
    override-build: |
      # Workaround mikaey/mfst#5
      autoreconf -fi
      craftctl default
    build-packages:
      - autoconf
      - automake
      - libtool
      - pkg-config
      - uuid-dev
      - libudev-dev
      - libjson-c-dev
      - libncurses-dev
      - libmariadb-dev
    stage-packages:
      - libudev1
      - libjson-c5
      - libmariadb3
      - libncurses6
      - libncursesw6
      - libtinfo6
      - libuuid1
